### ISSUE TITLE
Let radar subscribe to odom

### ISSUE THREAD

**Issue by MCFurry** [bosch-engineering/off_highway_sensor_drivers#3]
Thanks a lot for this repo!

One feature request though, the sender node of the ohw_radar currently subscribes to a `geometry_msgs/msg/twist_stamped` message to send ego velocity and yaw rate to the radar. [Link here](https://github.com/bosch-engineering/off_highway_sensor_drivers/blob/0a1fd5847c8d3bf2aa3e7d2506377f365a5c2226/off_highway_radar/src/sender.cpp#L34)

Would it be possible to add an additional subscriber to odom (`nav_msgs/msg/Odometry`)? 
A lot of ROS implementations have some kind of localization filter running and thereby have an odometry message which would be the perfect input.
Currently we have to write a small relay node that extracts the velocity part of our odom message and send this to your node as a twist_stamped message.

**Comment by daniel4ohw** [comment]
Hello @MCFurry 
thank you very much for your feedback.
We will analyze your proposal and let you know how we will proceed.
At the moment we are still working on a few tasks that we need to complete.
Greetings Daniel

**Comment by daniel4ohw** [comment]
Hi @MCFurry 
starting with version 0.6.0, with the switch to composable nodes,you can now change / add subscribers. 
An example can be found here https://github.com/bosch-engineering/off_highway_sensor_drivers/tree/humble-devel/off_highway_sensor_drivers_examples/src/off_highway_radar_examples

**Comment by mbharatheesha** [comment]
@daniel4ohw I was wondering about the underlying rationale behind putting the velocity extraction code in the examples package. Indeed the solution works, but one will have to add the `off_highway_sensor_drivers_examples` package as (at least) a runtime depenedency to use the velocity extraction composable node.

If that node is put into the `off_highway_radar` package, it will all be in one place was my thinking. Of course, I can imagine that the conversion itself is not semantically relevant in the radar package strictly speaking. But as mentioned in OP above it is very likely that many ROS applications use some kind of a filter to generate odometry which in turn contains ego velocity.

I was considering making a PR to move the node into `off_highway_radar` package, but I thought I check here to understand the rationale before making the PR.

**Comment by rcp1-beg** [comment]
Hi @mbharatheesha,

indeed, the rationale is to keep our driver interface as minimal as possible.

Odometry messages contain many additional fields that our current sensors do not use. Therefore, the task of subscribing to an odometry message (which adds a dependency) and extracting only a portion of it (a process that is not explicit to the user) should be handled by the application orchestrating the driver, rather than by the driver itself. This is especially relevant in compute-limited embedded environments.

Moreover, the off_highway_sensor_drivers_examples package is not intended for direct use in production. Instead, it is meant to help users implement the field extraction mentioned above within their own code. See README:

> Example to demonstrate how velocity information from messages other than geometry_msgs::msg::TwistStamped can be passed to the off_highway_radar driver.

You stated:

> that many ROS applications use some kind of a filter to generate odometry which in turn contains ego velocity

So, for example, one solution would be to add the velocity extraction logic directly to this filter.

I am aware that this is not ideal from a usability standpoint, but I think it is architecturally better in the long run. I would hope that `topic_tools/transform` would be rewritten in C++, so one could use this here with intra-process communication and no additional code.
